version: "3.9"
services:
  service:
    build: .
    image: "atforestry/${IMAGE_NAME}"
    ports:
      - "8000:8000" 
    volumes:
      - ./src:/app/src
    environment: 
      - PLANET_API_KEY=${PLANET_API_KEY}